with OVERDRAFTTABLE AS 
                (
                    SELECT LAST_DAY(TRANSACTIONDATE)-1 TRANSACTIONDATE, NULL TRANSACTION_TYPE,  NULL AMOUNT, NULL BALANCE
                      FROM (SELECT max(TRANSACTIONDATE) TRANSACTIONDATE FROM BALANCE_SHEET)
                    UNION ALL 
                    SELECT TRANSACTIONDATE, TRANSACTION_TYPE, AMOUNT, BALANCE
                      FROM BALANCE_SHEET
                    UNION ALL 
                    SELECT TRUNC(TRANSACTIONDATE,'MM')-1 TRANSACTIONDATE, NULL TRANSACTION_TYPE,  NULL AMOUNT, NULL BALANCE
                     FROM (SELECT TRUNC(max(TRANSACTIONDATE)) TRANSACTIONDATE FROM BALANCE_SHEET)
                ),

GAPTABLE AS 
                (
                   SELECT  TRANSACTIONDATE, TRANSACTION_TYPE, AMOUNT, BALANCE,
                           TRUNC(LEAD(TRANSACTIONDATE,1,TRANSACTIONDATE) OVER(ORDER BY TRANSACTIONDATE)) - TRUNC(TRANSACTIONDATE) + 1  GAP
                     FROM  OVERDRAFTTABLE
                ),

BALANCE_SHEET_ALL_DAYS AS
               ( SELECT  TO_CHAR(CASE WHEN LEVELL  = GAP THEN TRANSACTIONDATE ELSE TRUNC(TRANSACTIONDATE) + LEVELL  END,'DD.MM.YYYY HH24:MI:SS') TRANSACTIONDATE2,
                         CASE WHEN LEVELL  = GAP THEN TRANSACTION_TYPE END TRANSACTION_TYPE2,
                         CASE WHEN LEVELL  = GAP THEN AMOUNT END AMOUNT2,
                         BALANCE BALANCE2
                  FROM  GAPTABLE,
                      LATERAL (
                              SELECT  LEVEL LEVELL                        
                              FROM  DUAL                  
                              CONNECT BY LEVEL <= GAP
                              )
                ORDER BY CASE WHEN LEVELL = GAP THEN TRANSACTIONDATE ELSE TRUNC(TRANSACTIONDATE) + LEVELL END DESC
               )

SELECT  TO_DATE(TRANSACTIONDATE2, 'DD.MM.YYYY HH24:MI:SS') TRANSACTIONDATE2, 
        AMOUNT2, 
        BALANCE2, 
        LAG(BALANCE2, 1, BALANCE2) OVER (ORDER BY TO_DATE(TRANSACTIONDATE2, 'DD.MM.YYYY HH24:MI:SS')) BALANCEPREVIOUS
 FROM  BALANCE_SHEET_ALL_DAYS 
ORDER BY TO_DATE(TRANSACTIONDATE2, 'DD.MM.YYYY HH24:MI:SS') DESC