with OVERDRAFTTABLE AS 
                (
                    SELECT LAST_DAY(TRANSACTIONDATE)-1 TRANSACTIONDATE, NULL TRANSACTION_TYPE,  NULL AMOUNT, NULL BALANCE
                      FROM (SELECT max(TRANSACTIONDATE) TRANSACTIONDATE FROM BALANCE_SHEET)
                    UNION ALL 
                    SELECT TRANSACTIONDATE, TRANSACTION_TYPE, AMOUNT, BALANCE
                      FROM BALANCE_SHEET
                    UNION ALL 
                    SELECT TRUNC(TRANSACTIONDATE,'MM')-1 TRANSACTIONDATE, NULL TRANSACTION_TYPE,  NULL AMOUNT, NULL BALANCE
                     FROM (SELECT TRUNC(max(TRANSACTIONDATE)) TRANSACTIONDATE FROM BALANCE_SHEET)
                )
SELECT  TRANSACTIONDATE,
        TRANSACTION_TYPE
        AMOUNT,
        BALANCE,
        TRUNC(LEAD(TRANSACTIONDATE,1,TRANSACTIONDATE) OVER(ORDER BY TRANSACTIONDATE)) LEAD_DATE_TRUNCED,
        TRUNC(LEAD(TRANSACTIONDATE,1,TRANSACTIONDATE) OVER(ORDER BY TRANSACTIONDATE)) - TRUNC(TRANSACTIONDATE) + 1  GAP
  FROM  OVERDRAFTTABLE